KnowledgeBase/KnowledgeBase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls'), name='homepage'),
    path('knowledgebase/', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('mdeditor/', include('mdeditor.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

KnowledgeBase/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import HomePage, DetailViewNote, SearchResultsView

app_name = 'core'
urlpatterns = [
    path('', HomePage.as_view(), name='index'),
    path('<int:pk>/', DetailViewNote.as_view(), name='detail'),
    path('search/', SearchResultsView.as_view(), name='result_search'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

KnowledgeBase/homepage/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import HomePage

app_name = 'homepage'
urlpatterns = [
    path('', HomePage.as_view(), name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

KnowledgeBase/core/models.py
import os

from django.db import models
from mdeditor.fields import MDTextField

__all__ = {'City', 'Department', 'Category', 'Note'}


class City(models.Model):
    name = models.CharField(max_length=25, db_index=True, help_text='Название города')

    class Meta:
        verbose_name = "Город"
        verbose_name_plural = "Города"
        permissions = (('view', 'Право на просмотр'),)

    def __str__(self):
        return self.name


class Department(models.Model):
    name = models.CharField(max_length=100, db_index=True, help_text='Название отдела')

    class Meta:
        verbose_name = "Отдел"
        verbose_name_plural = "Отделы"
        permissions = (('view', 'Право на просмотр'),)

    def __str__(self):
        return self.name


class Category(models.Model):
    title = models.CharField(max_length=50, db_index=True, help_text='Имя категории')

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        permissions = (('view', 'Право на просмотр'),)

    def __str__(self):
        return self.title


class Note(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, help_text='Город')
    department = models.ForeignKey(Department, on_delete=models.CASCADE, help_text='Отдел')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, help_text='Категория')
    title = models.CharField(max_length=100, db_index=True, help_text='Заголовок')
    file = models.FileField(upload_to='files', blank=True, help_text='Прикрепленный файл')
    created = models.DateField(auto_now_add=True, help_text='Дата создания заметки')
    content_markdown = MDTextField()

    class Meta:
        verbose_name = "Заметка"
        verbose_name_plural = "Заметки"
        permissions = (('view', 'Право на просмотр'),)

    def __str__(self):
        return self.title

    # def download_file(self):
    #     path_to_file = os.path.join('/homepage/portal/media/', self.file.name)
    #     return path_to_file.replace('/homepage/portal', '')

KnowledgeBase/homepage/models.py
from django.db import models

# Create your models here.

KnowledgeBase/core/forms.py
from django import forms
from mdeditor.fields import MDTextFormField


class MDEditorForm(forms.Form):
    content = MDTextFormField()

KnowledgeBase/core/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, redirect
from django.views.generic import DetailView, ListView
from django.views.generic.base import View

from .forms import MDEditorForm
from .models import City, Department, Category, Note

__all__ = {'HomePage', 'DetailViewNote', 'SearchResultsView'}


class HomePage(PermissionRequiredMixin, View):
    permission_required = ('core.view',)

    @staticmethod
    @login_required
    def get(request: HttpRequest) -> HttpResponse:
        cities = City.objects.all()
        departments = Department.objects.all()
        categories = Category.objects.all()
        notes = Note.objects.all()
        form = MDEditorForm
        context = dict(cities=cities, departments=departments, categories=categories, notes=notes, form=form)

        return render(request, 'core/index.html', context=context)

    def post(self, request: HttpRequest) -> HttpResponse:
        select_city = request.POST['select_city']
        select_department = request.POST['select_department']
        select_category = request.POST['select_category']
        if request.POST['input_title']:
            input_title = request.POST['input_title']
        else:
            messages.error(request, 'Требуется ввести заголовок!')
            return redirect('core:index')
        if request.POST['input_note']:
            input_note = request.POST['input_note']
        else:
            messages.error(request, 'Требуется ввести текст заметки!')
            return redirect('core:index')

        object_city = City.objects.get(name=select_city)
        object_department = Department.objects.get(name=select_department)
        object_category = Category.objects.get(title=select_category)

        if request.FILES:
            user_upload_file = request.FILES['user_upload_file']
            object_note = Note(city=object_city, department=object_department, category=object_category,
                               file=user_upload_file, title=input_title, content_markdown=input_note)
        else:
            object_note = Note(city=object_city, department=object_department, category=object_category,
                               title=input_title, content_markdown=input_note)
        object_note.save()

        messages.info(request, 'Ваша запись успешно добавлена в базу!')
        return redirect('core:index')


class DetailViewNote(PermissionRequiredMixin, DetailView):
    model = Note
    template_name = 'core/detail.html'
    permission_required = ('core.view',)


class SearchResultsView(PermissionRequiredMixin, ListView):
    model = Note
    template_name = 'core/result_search.html'
    permission_required = ('core.view',)

    @login_required
    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Note.objects.filter(
            Q(title__icontains=query) | Q(content__icontains=query)
        )
        return object_list

KnowledgeBase/homepage/views.py
__all__ = {'HomePage'}

from django.http import HttpResponse, HttpRequest
from django.shortcuts import render
from django.views.generic.base import View


class HomePage(View):
    @staticmethod
    def get(request: HttpRequest) -> HttpResponse:
        return render(request, 'homepage/index.html')

KnowledgeBase/templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Частный портал</title>
    <link rel="shortcut icon" type="image/ico" href="{% static 'images/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'css/bulma.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css'>
    <link rel="stylesheet" href="{% static 'css/style_for_list_category.css' %}">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <script src='https://code.jquery.com/jquery-2.2.4.min.js'></script>
    <script src="{% static 'js/index.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}
</head>
<body>

<script>
    document.addEventListener('DOMContentLoaded', () => {

  // Get all "navbar-burger" elements
  const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

  // Check if there are any navbar burgers
  if ($navbarBurgers.length > 0) {

    // Add a click event on each of them
    $navbarBurgers.forEach( el => {
      el.addEventListener('click', () => {

        // Get the target from the "data-target" attribute
        const target = el.dataset.target;
        const $target = document.getElementById(target);

        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
        el.classList.toggle('is-active');
        $target.classList.toggle('is-active');
      });
    });
  }
});
</script>

<nav class="navbar is-info" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
           data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item" href="{% url 'homepage:index' %}">
                Главная
            </a>
        </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
            {% if user.is_authenticated %}
            <a class="button is-light" href="{% url 'logout' %}">
                Выйти
            </a>
            {% else %}
            <a class="button is-primary">
            <strong>Зарегистрироваться</strong>
            </a>
            <a class="button is-light" href="{% url 'login' %}">
                Войти
            </a>
            {% endif %}
        </div>
      </div>
    </div>

</nav>

<!--<section class="hero is-primary is-bold">-->
<section class="hero is-bold">
    <div class="hero-body">
        <div class="container">

            <div class="columns is-1">
                <div class="column is-1">
                    <img src="{% static 'images/logo_example.jpg' %}" height="120" width="120">
                </div>
                <div class="column is-11">
                    <h1 class="title">
                        Частный портал
                    </h1>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
{% block content %}
{% endblock %}
    </div>
</section>
</body>
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>Частный портал</strong> - создан 25.02.2020 г.
    </p>
  </div>
</footer>
</html>

KnowledgeBase/templates/core/detail.html
{% extends 'base.html' %}

{% block scripts %}
<script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.8.0/marked.min.js'></script>
{% endblock scripts %}

{% block content %}

<!-- Скрипт для преобразования текста в markdown -->
<script type="text/javascript">
    $(document).ready(function(){
        $(".content-markdown").each(function(){
            var content = $(this).text()
            var markedContent = marked(content)
            $(this).html(markedContent)
        })
    })
</script>

<div class="content is-medium">
    <h1>{{ note.title }}</h1>

    <div id="meta" class="field is-grouped is-grouped-multiline">
        <div class="control">
            <div class="tags has-addons">
                <span class="tag">Город</span>
                <span class="tag is-success">{{ note.city }}</span>
            </div>
        </div>
        <div class="control">
            <div class="tags has-addons">
                <span class="tag">Отдел</span>
                <span class="tag is-success">{{ note.department }}</span>
            </div>
        </div>
        <div class="control">
            <div class="tags has-addons">
                <span class="tag">Категория</span>
                <span class="tag is-success">{{ note.category }}</span>
            </div>
        </div>
        <div class="control">
            <div class="tags has-addons">
                <span class="tag">Дата создания</span>
                <span class="tag is-success">{{ note.created }}</span>
            </div>
        </div>
    </div>
    <br>

    <p class="content-markdown">{{ note.content_markdown }}</p>

    {% if note.file %}
    <p><a class="button is-link is-light" href="{{ note.download_file }}">{{ note.file }}</a></p>
    {% endif %}
    <br>
    <a class="button is-info" href="{% url 'core:index' %}">Вернуться на главную</a>

</div>

{% endblock %}

KnowledgeBase/templates/core/index.html
{% extends 'base.html' %}
{% block title %}- База Знаний{% endblock %}

{% block scripts %}
{% endblock scripts %}

{% block content %}
{% if user.is_authenticated %}

<!-- Скрипт для закрытия уведомления -->
<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', () => {
  (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
    $notification = $delete.parentNode;

    $delete.addEventListener('click', () => {
      $notification.parentNode.removeChild($notification);
    });
  });
});
</script>

<div class="columns">
    <div class="column">
        <article class="panel is-info">
            <p class="panel-heading">
                Заметки
            </p>
            <div class="field has-addons">
                <p class="control is-expanded">
                <form class="search" action="{% url 'core:result_search' %}" method="get">
                    <input class="input is-info" name="q" type="text" placeholder="Поиск">
                </form>
                </p>
            </div>

            <ul class="accordion-menu">
                {% for category in categories %}
                <li>
                    <div class="dropdownlink">{{ category }}
                        <i class="fa fa-chevron-down" aria-hidden="true"></i>
                    </div>
                    <ul class="submenuItems">
                        {% for note in notes %}
                        {% if note.category.id == category.id %}
                        <li><a href="{% url 'core:detail' note.id %}">
                            <i class="far fa-sticky-note"></i> {{ note }}</a></li>
                        {% endif %}
                        {% endfor %}
                    </ul>
                </li>
                {% endfor %}
            </ul>
        </article>

    </div>
    <div class="column">

        {% if messages %}
        {% for message in messages %}
        <div class="notification {% if message.tags == 'error' %}is-danger{% else %}is-primary{% endif %}">
            <button class="delete"></button>
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}

        <form action="{% url 'core:index' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="field">
                <label class="label">Выберите город</label>
                <div class="control">
                    <div class="select">
                        <select name="select_city">
                            {% for city in cities %}
                            <option>{{ city }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>

            <div class="field">
                <label class="label">Выберите отдел</label>
                <div class="control">
                    <div class="select">
                        <select name="select_department">
                            {% for department in departments %}
                            <option>{{ department }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>

            <div class="field">
                <label class="label">Выберите категорию</label>
                <div class="control">
                    <div class="select">
                        <select name="select_category">
                            {% for category in categories %}
                            <option>{{ category }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>

            <div class="field">
                <label class="label">Введите заголовок</label>
                <div class="control">
                    <input class="input" type="text" name="input_title" placeholder="Заголовок заметки">
                </div>
            </div>

            <div class="file">
                <label class="file-label">
                    <input class="file-input" type="file" name="user_upload_file">
                    <span class="file-cta">
                        <span class="file-icon">
                            <i class="fas fa-upload"></i>
                        </span>
                        <span class="file-label">Выберите файл (если нужно)</span>
                    </span>
                </label>
            </div>

            <div class="field">
                <label class="label">Сообщение</label>
                <div class="control">
                    <textarea class="textarea" name="input_note" placeholder="Опишите проблему"></textarea>
                </div>
            </div>

            <div class="field is-grouped">
                <div class="control">
                    <input class="button is-link" type="submit" value="Сохранить в базу">
                </div>
            </div>
        </form>

    </div>
</div>

{% else %}
<div class="tile is-parent">
    <article class="tile is-child box">
        <section class="hero is-info is-bold">
            <div class="hero-body">
                <div class="container">
                    <h1 class="title">
                        Войдите в свой аккаунт
                    </h1>
                    <form method="post" action="{% url 'login' %}">
                        {% csrf_token %}
                        <div class="field">
                            <label for="id_username" class="label">Имя пользователя:</label>
                            <div class="control">
                                <input class="input" type="text" name="username" autofocus="" autocapitalize="none"
                                       autocomplete="username" maxlength="150" required="" id="id_username">
                            </div>
                        </div>
                        <div class="field">
                            <label for="id_password" class="label">Пароль:</label>
                            <div class="control">
                                <input class="input" type="password" name="password" autocomplete="current-password"
                                       required=""
                                       id="id_password">
                            </div>
                        </div>
                        <input type="submit" value="Войти" class="button is-info is-inverted is-outlined"/>
                        <input type="hidden" name="next" value="{{ next }}"/>
                    </form>
                </div>
            </div>
        </section>
    </article>
</div>
{% endif %}

{% endblock %}

KnowledgeBase/templates/core/result_search.html
{% extends 'base.html' %}
{% block content %}

<h1>Результаты поиска:</h1>

<table class="table">
  <thead>
    <tr>
      <th><abbr title="Position">#</abbr></th>
      <th>Заголовок</th>
      <th><abbr title="Category">Категория</abbr></th>
      <th><abbr title="Date">Дата создания</abbr></th>
      <th><abbr title="City">Город</abbr></th>
      <th><abbr title="Departament">Отдел</abbr></th>
      <th><abbr title="Content">Содержимое</abbr></th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th><abbr title="Position">#</abbr></th>
      <th>Заголовок</th>
      <th><abbr title="Category">Категория</abbr></th>
      <th><abbr title="Date">Дата создания</abbr></th>
      <th><abbr title="City">Город</abbr></th>
      <th><abbr title="Departament">Отдел</abbr></th>
      <th><abbr title="Content">Содержимое</abbr></th>
    </tr>
  </tfoot>
  <tbody>
  {% for note in object_list %}
  <tr>
      <th>{{ forloop.counter }}</th>
      <td><a href="{% url 'core:detail' note.id %}" title="{{ note.title }}">{{ note.title }}</a></td>
      <td>{{ note.category }}</td>
      <td>{{ note.created }}</td>
      <td>{{ note.city }}</td>
      <td>{{ note.department }}</td>
      <td>{{ note.content }}</td>
  </tr>
  {% endfor %}
 </tbody>
</table>
<br>
<a class="button is-info" href="{% url 'core:index' %}">Вернуться на главную</a>
{% endblock %}

KnowledgeBase/templates/homepage/index.html
{% extends 'base.html' %}
{% block content %}
<div class="columns">
    <div class="column">
        <div class="card">
            <header class="card-header">
                <p class="card-header-title">
                    База знаний
                </p>
            </header>
            <div class="card-content">
                <div class="content">
                    Для сохранения знаний
                </div>
            </div>
            <footer class="card-footer">
                {% if perms.core.view %}
                <a href="{% url 'core:index' %}" class="card-footer-item">Открыть</a>
                {% else %}
                <p class="card-footer-item">У вас нет прав на этот модуль</p>
                {% endif %}
            </footer>
        </div>
    </div>
    <div class="column">
        <div class="card">
            <header class="card-header">
                <p class="card-header-title">
                    Админка
                </p>
            </header>
            <div class="card-content">
                <div class="content">
                    Панель администратора
                </div>
            </div>
            <footer class="card-footer">
                {% if user.is_staff %}
                <a href="{% url 'admin:index' %}" class="card-footer-item">Открыть</a>
                {% else %}
                <p class="card-footer-item">У вас нет прав на этот модуль</p>
                {% endif %}
            </footer>
        </div>
    </div>
</div>
{% endblock %}